services:
    triplestore-db:
      image: redis:8.0
      container_name: sentris-triplestore-db
      command: redis-server /etc/redis/redis.conf
      volumes:
        - ./data:/data/dumb.rdb:u+rwx
        - ../SSL/ca-cert.pem:/etc/certs/ca-cert.pem:ro
        - ../SSL/triplestore-redis-cert.pem:/etc/certs/redis-cert.pem:ro
        - ../SSL/triplestore-redis-key.pem:/etc/certs/redis-key.pem:ro
        - ../SSL/triplestore-redis.dh:/etc/certs/redis.dh:ro
        - ./DB/redis.conf:/etc/redis/redis.conf:ro
      expose:
        - "6379"
      networks:
        - sentris-triplestore-backend
      environment:
        REDIS_TLS_ENABLED: "yes"
        SKIP_FIX_PERMS: 1
        
    triplestore-api:
      depends_on:
        - triplestore-db
      image: ${DOCKER_REGISTRY}/sentris-triplestore-api
      container_name: sentris-triplestore-api
      command: >
        sh -c "echo 'org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource' >> conf/catalina.properties && catalina.sh run"
      volumes:
        - ../SSL/triplestore-truststore.ks:/usr/local/tomcat/ssl/triplestore-truststore.ks
        - ../SSL/triplestore-cert.pem:/usr/local/tomcat/ssl/triplestore-cert.pem
        - ../SSL/triplestore-key.pem:/usr/local/tomcat/ssl/triplestore-key.pem
        - ./server.xml:/usr/local/tomcat/conf/server.xml
        - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh
      expose:
        - "8443"
      networks:
        - sentris-triplestore-backend
        - sentris-triplestore-frontend
        - sentris-iam-provider-frontend
        - sentris-vault-frontend
      env_file:
        - ./system-properties.env
        - ../Secrets/triplestore-secrets.env

volumes:
    data:

networks:
  sentris-triplestore-backend:
    name: sentris-triplestore-backend
    driver: bridge
  sentris-triplestore-frontend:
    name: sentris-triplestore-frontend
    driver: bridge
  sentris-iam-provider-frontend:
    name: sentris-iam-provider-frontend
    external: true
  sentris-vault-frontend:
    name: sentris-vault-frontend
    external: true