version: "3.9"

services:
    db:
      image: ${DOCKER_REGISTRY}/secure-storage-db
      container_name: secure-storage-db
      volumes:
        - ./db_data:/data/db
      networks:
        - backend
      env_file:
        - Secrets/db-secrets.env

    api:
      depends_on:
        - db
      image: ${DOCKER_REGISTRY}/secure-storage
      container_name: secure-storage-api
      command: >
        sh -c "echo 'org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource' >> conf/catalina.properties && catalina.sh run"
      volumes:
        - ./SSL:/usr/local/tomcat/ssl
        - ./API/server.xml:/usr/local/tomcat/conf/server.xml
      ports:
        - "8443:8443"
      networks:
        - backend
      env_file:
        - API/system-properties.env
        - Secrets/api-secrets.env

volumes:
    db_data:

networks:
  backend:
    name: secure-storage-backend
    driver: bridge