version: "3.9"

services:
    triplestore_db:
      image: redis:latest
      container_name: triplestore-db
      command: redis-server ../usr/local/etc/redis/redis.conf
      ports:
        - 6379:6379
      volumes:
        - ./db_data:/data
        - ./SSL/ca-cert.pem:/usr/local/etc/redis/tls/ca-cert.pem
        - ./SSL/redis-cert.pem:/usr/local/etc/redis/tls/redis-cert.pem
        - ./SSL/redis-key.pem:/usr/local/etc/redis/tls/redis-key.pem
        - ./SSL/redis.dh:/usr/local/etc/redis/tls/redis.dh
        - ./DB/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        - triplestore-net
      environment:
        REDIS_TLS_ENABLED: "yes"

    triplestore_api:
      depends_on:
        - triplestore-db
      image: ${DOCKER_REGISTRY}/SEnTri/triplestore-api
      container_name: triplestore-api
      command: >
        sh -c "echo 'org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource' >> conf/catalina.properties && catalina.sh run"
      volumes:
        - ./SSL/triplestore-truststore.ks:/usr/local/tomcat/ssl/triplestore-truststore.ks
        - ./SSL/triplestore-cert.pem:/usr/local/tomcat/ssl/triplestore-cert.pem
        - ./SSL/triplestore-key.pem:/usr/local/tomcat/ssl/triplestore-key.pem
        - ./Triplestore/server.xml:/usr/local/tomcat/conf/server.xml
      expose:
        - "8443"
      networks:
        - triplestore-frontend
        - triplestore-backend
        - proxy-backend
      env_file:
        - Triplestore/system-properties.env
        - Secrets/triplestore-secrets.env

    proxy:
      image: ${DOCKER_REGISTRY}/SEnTri/proxy
      container_name: proxy
      command: >
        sh -c "echo 'org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource' >> conf/catalina.properties && catalina.sh run"
      volumes:
        - ./SSL/proxy-truststore.ks:/usr/local/tomcat/ssl/proxy-truststore.ks
        - ./SSL/proxy-cert.pem:/usr/local/tomcat/ssl/proxy-cert.pem
        - ./SSL/proxy-key.pem:/usr/local/tomcat/ssl/proxy-key.pem
        - ./Proxy/server.xml:/usr/local/tomcat/conf/server.xml
      ports:
        - "8443"
      networks:
        - proxy-backend
        - proxy-frontend
      env_file:
        - Proxy/system-properties.env
        - Secrets/proxy-secrets.env

    data_owner:
      image: ${DOCKER_REGISTRY}/SEnTri/data-owner
      container_name: data-owner
      command: >
        sh -c "echo 'org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource' >> conf/catalina.properties && catalina.sh run"
      volumes:
        - ./SSL/data-owner-truststore.ks:/usr/local/tomcat/ssl/data-owner-truststore.ks
        - ./SSL/data-owner-cert.pem:/usr/local/tomcat/ssl/data-owner-cert.pem
        - ./SSL/data-owner-key.pem:/usr/local/tomcat/ssl/data-owner-key.pem
        - ./DataOwner/server.xml:/usr/local/tomcat/conf/server.xml
      ports:
        - "8080:8443"
      networks:
        - triplestore-frontend
      env_file:
        - DataOwner/system-properties.env
        - Secrets/data-owner-secrets.env

volumes:
    db_data:

networks:
  triplestore-backend:
    name: triplestore-backend
    driver: bridge
  triplestore-frontend:
    name: triplestore-frontend
    driver: bridge
  proxy-backend:
    name: proxy-backend
    driver: bridge
  proxy-frontend:
    name: proxy-frontend
    driver: bridge