version: "3.9"

services:
    db:
      image: ${DOCKER_REGISTRY}/secure-storage-db
      container_name: secure-storage-db
      volumes:
        - ./db_data:/data/db
      networks:
        - backend
      env_file:
        - Secrets/db-secrets.env
      environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
        - MONGO_INITDB_DATABASE
        - DB_USER
        - DB_PWD
        - DB_NAME

    api:
      depends_on:
        - db
      image: ${DOCKER_REGISTRY}/secure-storage
      container_name: secure-storage-api
      volumes:
        - ./SSL:/usr/local/tomcat/ssl
        - ./API/server.xml:/usr/local/tomcat/conf/server.xml
      ports:
        - "8443:8443"
      networks:
        - backend
      env_file:
        - API/system-properties.env
        - Secrets/api-secrets.env
      environment:
        - DB_NAME
        - DB_CONNECTION
        - SERVER_CERT_PWD
volumes:
    db_data:

networks:
  backend:
    name: secure-storage-backend
    driver: bridge