services:
    iam-provider-db:
      image: redis:8.0
      container_name: sentris-iam-provider-db
      command: redis-server /etc/redis/redis.conf
      volumes:
        - ./data:/data/dumb.rdb:u+rwx
        - ../SSL/ca-cert.pem:/etc/certs/ca-cert.pem:ro
        - ../SSL/iam-provider-redis-cert.pem:/etc/certs/redis-cert.pem:ro
        - ../SSL/iam-provider-redis-key.pem:/etc/certs/redis-key.pem:ro
        - ../SSL/iam-provider-redis.dh:/etc/certs/redis.dh:ro
        - ./DB/redis.conf:/etc/redis/redis.conf:ro
      expose:
        - "6379"
      networks:
        - sentris-iam-provider-backend
      environment:
        REDIS_TLS_ENABLED: "yes"
        SKIP_FIX_PERMS: 1
        
    iam-provider-api:
      depends_on:
        - iam-provider-db
      image: ${DOCKER_REGISTRY}/sentris-iam-provider-api
      container_name: sentris-iam-provider-api
      command: >
        sh -c "echo 'org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource' >> conf/catalina.properties && catalina.sh run"
      volumes:
        - ../SSL/iam-provider-truststore.ks:/usr/local/tomcat/ssl/iam-provider-truststore.ks
        - ../SSL/iam-provider-cert.pem:/usr/local/tomcat/ssl/iam-provider-cert.pem
        - ../SSL/iam-provider-key.pem:/usr/local/tomcat/ssl/iam-provider-key.pem
        - ./server.xml:/usr/local/tomcat/conf/server.xml
        - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh
      ports:
        - "8091:8443"
      networks:
        - sentris-iam-provider-backend
        - sentris-iam-provider-frontend
      env_file:
        - ./system-properties.env
        - ../Secrets/iam-provider-secrets.env

volumes:
    data:

networks:
  sentris-iam-provider-backend:
    name: sentris-iam-provider-backend
    driver: bridge
  sentris-iam-provider-frontend:
    name: sentris-iam-provider-frontend
    driver: bridge