services:
  client-api:
    image: ${DOCKER_REGISTRY}/sentri-client-api
    container_name: sentri-client
    command: >
      sh -c "echo 'org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource' >> conf/catalina.properties && catalina.sh run"
    volumes:
      - ../SSL/client-truststore.ks:/usr/local/tomcat/ssl/client-truststore.ks
      - ../SSL/client-cert.pem:/usr/local/tomcat/ssl/client-cert.pem
      - ../SSL/client-key.pem:/usr/local/tomcat/ssl/client-key.pem
      - ./server.xml:/usr/local/tomcat/conf/server.xml
    ports:
      - "8080:8443"
    networks:
      - sentri-client-frontend
      - sentri-vault-frontend
      - sentri-iam-provider-frontend
      - sentri-triplestore-frontend
    env_file:
      - ./system-properties.env
      - ../Secrets/client-secrets.env

networks:
  sentri-client-frontend:
    name: sentri-client-frontend
    driver: bridge
  sentri-vault-frontend:
    name: sentri-vault-frontend
    external: true
  sentri-iam-provider-frontend:
    name: sentri-iam-provider-frontend
    external: true
  sentri-triplestore-frontend:
    name: sentri-triplestore-frontend
    external: true
  