version: "3.9"

services:
    proxy-db:
      image: redis:latest
      container_name: sentri-proxy-db
      command: redis-server ../usr/local/etc/redis/redis.conf
      volumes:
        - ./data:/data
        - ../SSL/ca-cert.pem:/usr/local/etc/redis/tls/ca-cert.pem
        - ../SSL/redis-cert.pem:/usr/local/etc/redis/tls/redis-cert.pem
        - ../SSL/redis-key.pem:/usr/local/etc/redis/tls/redis-key.pem
        - ../SSL/redis.dh:/usr/local/etc/redis/tls/redis.dh
        - ./DB/redis.conf:/usr/local/etc/redis/redis.conf
      expose:
        - "6379"
      networks:
        - sentri-proxy-backend
      environment:
        REDIS_TLS_ENABLED: "yes"

    proxy-api:
      depends_on:
        - proxy-db
      image: ${DOCKER_REGISTRY}/sentri-proxy-api
      container_name: sentri-proxy-api
      command: >
        sh -c "echo 'org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource' >> conf/catalina.properties && catalina.sh run"
      volumes:
        - ../SSL/proxy-truststore.ks:/usr/local/tomcat/ssl/proxy-truststore.ks
        - ../SSL/proxy-cert.pem:/usr/local/tomcat/ssl/proxy-cert.pem
        - ../SSL/proxy-key.pem:/usr/local/tomcat/ssl/proxy-key.pem
        - ./server.xml:/usr/local/tomcat/conf/server.xml
      ports:
        - "8080:8443"
      networks:
        - sentri-proxy-backend
        - sentri-proxy-frontend
        - sentri-iam-provider-frontend
        - sentri-vault-frontend
      env_file:
        - ./system-properties.env
        - ../Secrets/proxy-secrets.env

volumes:
    data:

networks:
  sentri-proxy-backend:
    name: sentri-proxy-backend
    driver: bridge
  sentri-proxy-frontend:
    name: sentri-proxy-frontend
    driver: bridge
  sentri-iam-provider-frontend:
    name: sentri-iam-provider-frontend
    external: true
  sentri-vault-frontend:
    name: sentri-vault-frontend
    external: true