config:
  target: 'https://localhost'
  http:
    timeout: 3600 #1hour timeout
  plugins:
    metrics-by-endpoint: 
      useOnlyRequestNames: true
  processor: "./processor.js"
  variables:
    protocolEndpoints:
      - ""
      - "/encrypted/v1"
      - "/encrypted/v2"
  phases:
  - name: "Create users"   
    duration: 1
    arrivalCount: 1

before:
  flow:
    - log: "Initializing SEnTri IAM provider"
    - post:
        url: ":8081/IAMProvider/api/ctrl/init"
    - function: "genUser"        
    - post:
        url: ":8080/Client/api/ctrl/users"
        name: "create-user"
        headers:
          Content-Type: multipart/form-data
        json:
          username: "{{ username }}"
          password: "{{ password }}"
        afterResponse: "processGenUserReply"
    - post:                          
        url: ":8080/Client/api/ctrl/users/auth"
        name: "auth"
        headers:
          Content-Type: multipart/form-data
        json:
          username: "{{ username }}"
          password: "{{ password }}"
        afterResponse: "extractCookie"
        #Send user upgrade request
        #Auth w/ Admin
        #List upgrade requests
        #Accept upgrade request
scenarios:
 - name: 'Experimental evaluation'
   weight: 1
   flow:                         
      - loop:
        - function: "setDatasets"
        - function: "selectUser"
        - log: "Authenticating user"
        - post:                          
            url: ":8080/Client/api/ctrl/users/auth"
            name: "auth"
            headers:
              Content-Type: multipart/form-data
            json:
              username: "{{ username }}"
              password: "{{ password }}"
            afterResponse: "extractCookie"
        loop:
          - log: "Create triplestore"
          - post:                          
            url: ":8080/Client/api/triplestores{{ $loopElement }}"
            name: "create-triplestore"
            headers:
              Content-Type: multipart/form-data
              cookie: "[{{ session_cookie }}]"
            formData:
              issuer: "{{ username }}"
              triplestoreID: "{{ triplestoreID }}"

          - log: "Uploading dataset"
          - post:                          
            url: ":8080/Client/api/triplestores{{ $loopElement }}/upload?schema=false"
            name: "upload-dataset"
            headers:
              Content-Type: multipart/form-data
              cookie: "[{{ session_cookie }}]"
            beforeRequest: uploadDataset

          - log: "Uploading ontology"
          - post:                          
            url: ":8080/Client/api/triplestores{{ $loopElement }}/upload?schema=true"
            name: "upload-ontology"
            headers:
              Content-Type: multipart/form-data
              cookie: "[{{ session_cookie }}]"
            beforeRequest: uploadOntology

          

          whileTrue: "hasDataset"
        over: "protocolEndpoints"

      #Loop over datasets
        #Loop over count
          #Loop over protocols
            #Upload triplestore
              #Loop over queries
                #Loop over count
                  #Normal 
                  #Inference
            #Get info (size expansion)
            #Delete triplestore