config:
  target: 'https://localhost'
  http:
    timeout: 3600 #1hour timeout
  plugins:
    metrics-by-endpoint: 
      useOnlyRequestNames: true
  processor: "./processor.js"
  variables:
    SEnTriVersion:
      - "v1"
      - "v2"
  phases:
  - name: "Create users"   
    duration: 1
    arrivalCount: 1

before:
  flow:
    - log: "Initializing SEnTri IAM provider"
    - post:
        url: ":8081/IAMProvider/api/ctrl/init"
    - function: "genUser"        
    - post:
        url: ":8080/Client/api/users"
        name: "create-user"
        headers:
          Content-Type: multipart/form-data
        json:
          username: "{{ username }}"
          password: "{{ password }}"
        afterResponse: "processGenUserReply"
    - post:                          
        url: ":8080/Client/api/users/auth"
        name: "auth"
        headers:
          Content-Type: multipart/form-data
        json:
          username: "{{ username }}"
          password: "{{ password }}"
        afterResponse: "extractCookie"
        #Send user upgrade request
        #Auth w/ Admin
        #List upgrade requests
        #Accept upgrade request

after:
  flow:
    - function: "selectUser"        
    - post:                          
        url: ":8080/Client/api/users/auth"
        name: "auth"
        headers:
          Content-Type: multipart/form-data
        json:
          username: "{{ username }}"
          password: "{{ password }}"
        afterResponse: "extractCookie"
    - delete:
        url: ":8080/Client/api/users/{{ username }}"
        name: "delete-user"
        headers:
          cookie: "[{{ session_cookie }}]"

scenarios:
 - name: 'Experimental evaluation'
   weight: 1
   flow:                         
      - loop:
        - function: "setDatasets"
        - function: "selectUser"
        - log: "Authenticating user"
        - post:                          
            url: ":8080/Client/api/users/auth"
            name: "auth"
            headers:
              Content-Type: multipart/form-data
            json:
              username: "{{ username }}"
              password: "{{ password }}"
            afterResponse: "extractCookie"
        loop:
          - log: "Create triplestore"
          - post:                          
            url: ":8080/Client/api/triplestores/encrypted/{{ $loopElement }}"
            name: "create-triplestore"
            headers:
              Content-Type: multipart/form-data
              cookie: "[{{ session_cookie }}]"
            formData:
              issuer: "{{ username }}"
              triplestoreID: "{{ triplestoreID }}"
            beforeRequest: genTriplestore

          - log: "Uploading dataset"
          - post:                          
            url: ":8080/Client/api/triplestores/encrypted/{{ $loopElement }}/upload?schema=false"
            name: "upload-dataset"
            headers:
              Content-Type: multipart/form-data
              cookie: "[{{ session_cookie }}]"
            beforeRequest: uploadDataset

          - log: "Uploading ontology"
          - post:                          
            url: ":8080/Client/api/triplestores/encrypted/{{ $loopElement }}/upload?schema=true"
            name: "upload-ontology"
            headers:
              Content-Type: multipart/form-data
              cookie: "[{{ session_cookie }}]"
            beforeRequest: uploadOntology

          - log: "Deleting triplestore"
          - delete:                          
            url: ":8080/Client/api/triplestores/encrypted/{{ $loopElement }}/{{ triplestoreID }}/{{ username }}"
            name: "delete-triplestore"
            headers:
              cookie: "[{{ session_cookie }}]"
          
          whileTrue: "hasDataset"
        over: "SEnTriVersion"

      #Loop over datasets (lubm-1, lubm-5, lubm-10, lubm-20)
        #Loop over protocols
          #Repeat 10
            #Upload triplestore + ontology
            #Get info (size expansion)
            #Delete triplestore
      
      #Loop over datasets (lubm-1, lubm-5)
        #Loop over protocols
          #Loop over queries (normal & extra)
              #Repeat 10
                #Normal 
                #Inference

      #Loop over protocols
        #Loop over 5 users
          # Create triplestore + Upload (no ontology, lubm-1)
          # Loop over: [No access, read access, write access, remove write access, remove read access]
            # Share w/ access policy
            # Read          (test-name :is x?) expect :bot
            # Insert        (test-name :is :user-insert)
            # Read          (test-name :is x?) expect :user-insert
            # Delete        (test-name :is :user-insert)
            # Read          (test-name :is x?) expect :bot
            # Insert        (test-name :is :user-insert-2)
            # Read          (test-name :is x?) expect :user-insert-2
            # Delete/Insert (test-name :is :user-insert-2 ; :user-insert-3)
            # Read          (test-name :is x?) expect :user-insert-3
            #Delete where   (test-name :is :user-insert-3)
            # Read          (test-name :is x?) expect :bot
          # Transfer ownership to next user
        # Delete triplestore
                

# Upload test: 4 * 3 * 10 = 60uploads
# Lubm queries test: 12 * 10 * 20 = 2400 queries
# M/M setting test: 2 * 5 * 5 * 7 = 350 queries