version: "3.9"

services:
    proxy:
      image: ${DOCKER_REGISTRY}/sentri-proxy
      container_name: sentri-proxy
      command: >
        sh -c "echo 'org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource' >> conf/catalina.properties && catalina.sh run"
      volumes:
        - ./SSL/proxy-truststore.ks:/usr/local/tomcat/ssl/proxy-truststore.ks
        - ./SSL/proxy-cert.pem:/usr/local/tomcat/ssl/proxy-cert.pem
        - ./SSL/proxy-key.pem:/usr/local/tomcat/ssl/proxy-key.pem
        - ./server.xml:/usr/local/tomcat/conf/server.xml
      ports:
        - "8000:8443"
      networks:
        - sentri-proxy-network
      env_file:
        - ./system-properties.env
        - ../Secrets/proxy-secrets.env

networks:
  sentri-proxy-network:
    name: sentri-proxy-network
    driver: bridge